# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_seller_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='social',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
