# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20170211_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetail',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Product')),
                ('id', models.CharField(max_length=32)),
                ('hex_code', models.CharField(blank=True, max_length=16, null=True)),
                ('red', models.PositiveIntegerField(blank=True, null=True)),
                ('green', models.PositiveIntegerField(blank=True, null=True)),
                ('blue', models.PositiveIntegerField(blank=True, null=True)),
                ('hue', models.PositiveIntegerField(blank=True, null=True)),
                ('saturation', models.PositiveIntegerField(blank=True, null=True)),
                ('brightness', models.PositiveIntegerField(blank=True, null=True)),
                ('full_height', models.PositiveIntegerField(blank=True, null=True)),
                ('full_width', models.PositiveIntegerField(blank=True, null=True)),
                ('square_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
